package com.ibrahimekinci.barcrowd.data.local;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import java.util.Date;

/**
 * Room entity for LiveUpdate model, including sync status for offline handling.
 * Uses java.util.Date for timestamps.
 */
@Entity(tableName = "live_updates", indices = {@Index(value = {"venueId"})})
public class LiveUpdateEntity {

    @PrimaryKey
    @NonNull
    private String updateId; // This is the UUID generated by the app

    private String venueId;
    private String userId;
    private String crowdLevel;
    private String waitTime; // This is a String (e.g., "5-15") per your schema
    private String ageRange;
    private String description;
    private String mediaUrl;
    private String thumbnailUrl;
    private boolean isDeleted;
    private Date deletedAt; // Use java.util.Date

    // Denormalized data
    private String venueName;
    private String venueType;
    private String venueLogoUrl;

    // Timestamps
    private Date updatedAt;
    private Date createdAt;

    private boolean syncStatus;

    public LiveUpdateEntity() {
    }

    // --- Getters ---
    @NonNull
    public String getUpdateId() {
        return updateId;
    }

    public String getVenueId() {
        return venueId;
    }

    public String getUserId() {
        return userId;
    }

    public String getCrowdLevel() {
        return crowdLevel;
    }

    public String getWaitTime() {
        return waitTime;
    }

    public String getAgeRange() {
        return ageRange;
    }

    public String getDescription() {
        return description;
    }

    public String getMediaUrl() {
        return mediaUrl;
    }

    public String getThumbnailUrl() {
        return thumbnailUrl;
    }

    public boolean isDeleted() {
        return isDeleted;
    }

    public Date getDeletedAt() {
        return deletedAt;
    }

    public String getVenueName() {
        return venueName;
    }

    public String getVenueType() {
        return venueType;
    }

    public String getVenueLogoUrl() {
        return venueLogoUrl;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public boolean isSyncStatus() {
        return syncStatus;
    }

    // --- Setters ---
    public void setUpdateId(@NonNull String updateId) {
        this.updateId = updateId;
    }

    public void setVenueId(String venueId) {
        this.venueId = venueId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public void setCrowdLevel(String crowdLevel) {
        this.crowdLevel = crowdLevel;
    }

    public void setWaitTime(String waitTime) {
        this.waitTime = waitTime;
    }

    public void setAgeRange(String ageRange) {
        this.ageRange = ageRange;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setMediaUrl(String mediaUrl) {
        this.mediaUrl = mediaUrl;
    }

    public void setThumbnailUrl(String thumbnailUrl) {
        this.thumbnailUrl = thumbnailUrl;
    }

    public void setDeleted(boolean deleted) {
        this.isDeleted = deleted;
    }

    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    public void setVenueName(String venueName) {
        this.venueName = venueName;
    }

    public void setVenueType(String venueType) {
        this.venueType = venueType;
    }

    public void setVenueLogoUrl(String venueLogoUrl) {
        this.venueLogoUrl = venueLogoUrl;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public void setSyncStatus(boolean syncStatus) {
        this.syncStatus = syncStatus;
    }
}